local map = {}

map['a'] 		= 'A'
map['b'] 		= 'B'
map['c'] 		= 'C'
map['d'] 		= 'D'
map['e'] 		= 'E'
map['f'] 		= 'F'			
map['g'] 		= 'G'
map['h'] 		= 'H'
map['i'] 		= 'I'
map['j'] 		= 'J'
map['k'] 		= 'K'
map['l'] 		= 'L'
map['m'] 		= 'M'
map['n'] 		= 'N'
map['o'] 		= 'O'
map['p'] 		= 'P'
map['q'] 		= 'Q'
map['r'] 		= 'R'
map['s'] 		= 'S'
map['t'] 		= 'T'
map['u'] 		= 'U'
map['v'] 		= 'V'
map['w'] 		= 'W'
map['x'] 		= 'X'
map['y'] 		= 'Y'
map['z'] 		= 'Z'
map[' ']		= 'Space'
map['lshift'] 	= 'Left Shift'

return map